# action.yml
name: "Build Re:VIEW"
description: "Build Re:VIEW files and create the artifact with respective format."
icon: "anchor"
color: "blue"
inputs:
  build:
    description: "Directory to build"
    required: false
    default: "articles"
  dist:
    description: "Directory to dist"
    required: false
    default: "dist"
  format:
    description: "Output format"
    required: false
    default: "pdf"
  theme:
    description: "Theme for book"
    required: false
    default: "techbooster"
  paperSize:
    description: "Paper size for the book"
    required: false
    default: "A4"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.build }}
    - ${{ inputs.dist }}
    - ${{ inputs.format }}
    - ${{ inputs.theme }}
    - ${{ inputs.paperSize }}
